//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomeDetail
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContactInfo { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
    }
}
