//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagmentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventorySystemEntities1 : DbContext
    {
        public InventorySystemEntities1()
            : base("name=InventorySystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<CustomeDetail> CustomeDetails { get; set; }
    
        public virtual ObjectResult<UserDetailsSp_Result> UserDetailsSp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserDetailsSp_Result>("UserDetailsSp");
        }
    
        public virtual ObjectResult<Nullable<int>> getSessionSp(string sessionKey)
        {
            var sessionKeyParameter = sessionKey != null ?
                new ObjectParameter("SessionKey", sessionKey) :
                new ObjectParameter("SessionKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getSessionSp", sessionKeyParameter);
        }
    
        public virtual ObjectResult<UserLoginSp_Result> UserLoginSp(string epfNumber)
        {
            var epfNumberParameter = epfNumber != null ?
                new ObjectParameter("EpfNumber", epfNumber) :
                new ObjectParameter("EpfNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLoginSp_Result>("UserLoginSp", epfNumberParameter);
        }
    }
}
