//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public int TotalQuantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Date { get; set; }
    
        public virtual UserRegister UserRegister { get; set; }
    }
}
