//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderId { get; set; }
        public int BrandId { get; set; }
        public int ProductId { get; set; }
        public int ProductVariantId { get; set; }
        public decimal ItemPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductVariante ProductVariante { get; set; }
    }
}
