//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRegister()
        {
            this.UserSessions = new HashSet<UserSession>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string EPFNumber { get; set; }
        public string Nic { get; set; }
        public string Address { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public int UserStatus { get; set; }
        public string Password { get; set; }
        public string SaltPass { get; set; }
        public string ProfileImgName { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}
